# Generated by Django 6.0.7 on 2026-07-26 22:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alarm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=100)),
                ('time', models.TimeField()),
                ('repeat_days', models.CharField(blank=True, help_text="Comma-separated short day names, e.g. 'Mon,Wed,Fri'. Empty = one-time.", max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('sound', models.FileField(blank=True, null=True, upload_to='ringtones/')),
                ('snooze_minutes', models.PositiveIntegerField(default=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alarms', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
